Generic generators
hedgehogqa/fsharp-hedgehog-experimental pull request #78
Opened 2024-12-23 01:12 UTC by AlexeyRaga

2025-01-17 13:57 UTC, TysonMN commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
Why did you change the .NET version?

2025-01-18 00:15 UTC, AlexeyRaga commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
@TysonMN 
Because .NET 6 reached Out Of Support last year (in November, if I remember correctly).
.NET 8 is the next LTS which is supported by the end of 2026.

2025-01-18 13:54 UTC, TysonMN commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
So it wasn't needed to add this feature then?

If not, then please make a separate PR with a single commit that upgrades .NET.  In the commit message body, put the explanation that you have given here.

2025-01-18 14:17 UTC, AlexeyRaga commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
I can check, but I believe that it won't compile under .NET 6.
I can make a PR so we can upgrade to .NET 8 first, and then rebase this one on top.

2025-01-18 14:20 UTC, AlexeyRaga commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
I mean, .NET 8 is needed for the feature the way it is now. 
I just decided not to take any extra effort to add .NET 6 workarounds and simply use the officially supported version.

This way we can say that it is needed to add the feature.

2025-01-18 14:31 UTC, TysonMN commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
> I can make a PR so we can upgrade to .NET 8 first, and then rebase this one on top.

Yes. Two PRs in that order would be good.

2025-01-20 03:36 UTC, AlexeyRaga commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
@TysonMN 
OK, let's merge https://github.com/hedgehogqa/fsharp-hedgehog-experimental/pull/79 and then I'll rebase this one on top

2025-01-21 12:08 UTC, AlexeyRaga commented on .github/workflows/dotnet-core.yml
> +        dotnet-version: 8
@TysonMN As discussed, I have rebased this branch on top of .NET 8 enabled `master`.
Please check again.

2025-01-26 03:04 UTC, TysonMN requested changes

2025-01-26 03:04 UTC, TysonMN commented on src/Hedgehog.Experimental/Hedgehog.Experimental.fsproj
> +    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
Why is this needed?

2025-01-26 03:04 UTC, TysonMN commented on src/Hedgehog.Experimental/TypeShape.fs
> +let (|GenericShape|_|) (s: TypeShape) =
To every public function, please add documentation and an explicit return type

2025-01-26 11:51 UTC, AlexeyRaga commented on global.json
> +}
Standard .NET file to specify how to chose a .NET framework when multiple are installed.
https://learn.microsoft.com/en-us/dotnet/core/tools/global-json

2025-01-26 11:55 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/Hedgehog.Experimental.fsproj
> +    <PackageReference Include="System.Collections.Immutable" Version="9.0.0" />
It is a standard .NET library.
Without it I cannot have `ImmutableDictionary`. And I cannot have F#-specific `Map` because `Map` cannot have `Type` as a key.

2025-01-26 11:56 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/TypeShape.fs
> +let (|GenericShape|_|) (s: TypeShape) =
Oops, didn't mean it to be public. Will make it `internal` instead.

2025-01-26 11:59 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/Gen.fs
> +module internal GeneratorCollection =
I will undo this change and will keep the module public as it was before.

2025-01-26 12:02 UTC, AlexeyRaga commented on src/Hedgehog.Experimental.Tests/GenericGenTests.fs
> -
I didn't need it anymore, it overlaps.

2025-01-26 12:07 UTC, AlexeyRaga commented
@TysonMN will it be easier if I just squash these 3 commits into one?

2025-01-26 12:17 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/Gen.fs
> +    config
Done.

2025-01-26 12:31 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/TypeShape.fs
> +let (|GenericShape|_|) (s: TypeShape) =
Made the module `internal`, done.

2025-02-08 13:07 UTC, AlexeyRaga commented
@TysonMN it is better now?

2025-02-12 12:58 UTC, TysonMN commented on global.json
> +}
This is not related to this feature. Please add in a separate PR.

2025-02-12 13:05 UTC, TysonMN commented
> Will it be easier if I just squash these 3 commits into one?

No, that would be worse.  In fact, it would be better to split it up more.  I keep trying to identify things that can be merged now.

2025-02-12 13:07 UTC, TysonMN requested changes

2025-02-12 13:07 UTC, TysonMN commented on src/Hedgehog.Experimental/Gen.fs
> +  let internal empty = GeneratorCollection ImmutableDictionary.Empty
Adding `empty` is an improvement that can be made previously. Please create a PR for this change.

2025-02-12 21:54 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/Gen.fs
> +module internal GeneratorCollection =
We can do it after. Not needed for the proposed change.

2025-02-12 21:56 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/Gen.fs
> +  let internal empty = GeneratorCollection ImmutableDictionary.Empty
I'll split it into a separate commit, if you want.
But it is an internal member, and there was no use for it before...

2025-02-12 22:32 UTC, AlexeyRaga commented on src/Hedgehog.Experimental/Gen.fs
> +  let internal empty = GeneratorCollection ImmutableDictionary.Empty
Instead of making it a separate PR and going through an additional review process, I removed `empty` entirely and kept the logic the way it was.

2025-02-12 22:33 UTC, AlexeyRaga commented on global.json
> +}
I added it as a separate commit.

2025-03-08 05:15 UTC, merged